function varargout = SingleUserInterface(varargin)
% SINGLEUSERINTERFACE MATLAB code for SingleUserInterface.fig
%      SINGLEUSERINTERFACE, by itself, creates a new SINGLEUSERINTERFACE or raises the existing
%      singleton*.
%
%      H = SINGLEUSERINTERFACE returns the handle to a new SINGLEUSERINTERFACE or the handle to
%      the existing singleton*.
%
%      SINGLEUSERINTERFACE('CALLBACK',hObject,eventData,handles,...) calls the local
%      function named CALLBACK in SINGLEUSERINTERFACE.M with the given input arguments.
%
%      SINGLEUSERINTERFACE('Property','Value',...) creates a new SINGLEUSERINTERFACE or raises the
%      existing singleton*.  Starting from the left, property value pairs are
%      applied to the GUI before SingleUserInterface_OpeningFcn gets called.  An
%      unrecognized property name or invalid value makes property application
%      stop.  All inputs are passed to SingleUserInterface_OpeningFcn via varargin.
%
%      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
%      instance to run (singleton)".
%
% See also: GUIDE, GUIDATA, GUIHANDLES

% Edit the above text to modify the response to help SingleUserInterface

% Last Modified by GUIDE v2.5 07-Aug-2015 18:18:31

% Begin initialization code - DO NOT EDIT
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @SingleUserInterface_OpeningFcn, ...
                   'gui_OutputFcn',  @SingleUserInterface_OutputFcn, ...
                   'gui_LayoutFcn',  @SingleUserInterface_LayoutFcn, ...
                   'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end

if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end
end
% End initialization code - DO NOT EDIT


% --- Executes just before SingleUserInterface is made visible.
function SingleUserInterface_OpeningFcn(hObject, eventdata, handles, varargin)
% This function has no output args, see OutputFcn.
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% varargin   command line arguments to SingleUserInterface (see VARARGIN)

% Choose default command line output for SingleUserInterface
handles.output = hObject;

% Update handles structure
guidata(hObject, handles);
% UIWAIT makes SingleUserInterface wait for user response (see UIRESUME)
% uiwait(handles.figure1);
end

% --- Outputs from this function are returned to the command line.
function varargout = SingleUserInterface_OutputFcn(hObject, eventdata, handles) 
% varargout  cell array for returning output args (see VARARGOUT);
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Get default command line output from handles structure
varargout{1} = handles.output;
end


function edit9_Callback(hObject, eventdata, handles)
% hObject    handle to edit9 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of edit9 as text
%        str2double(get(hObject,'String')) returns contents of edit9 as a double
end

% --- Executes during object creation, after setting all properties.
function edit9_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit9 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
end


function DynUserFrequencyTxt_Callback(hObject, eventdata, handles)
% hObject    handle to DynUserFrequencyTxt (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of DynUserFrequencyTxt as text
%        str2double(get(hObject,'String')) returns contents of DynUserFrequencyTxt as a double
end

% --- Executes during object creation, after setting all properties.
function DynUserFrequencyTxt_CreateFcn(hObject, eventdata, handles)
% hObject    handle to DynUserFrequencyTxt (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
end



function DynUserToTxt_Callback(hObject, eventdata, handles)
% hObject    handle to DynUserToTxt (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of DynUserToTxt as text
%        str2double(get(hObject,'String')) returns contents of DynUserToTxt as a double
end

% --- Executes during object creation, after setting all properties.
function DynUserToTxt_CreateFcn(hObject, eventdata, handles)
% hObject    handle to DynUserToTxt (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
end


function DynStartSt_Callback(hObject, eventdata, handles)
% hObject    handle to DynStartSt (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of DynStartSt as text
%        str2double(get(hObject,'String')) returns contents of DynStartSt as a double
end

% --- Executes during object creation, after setting all properties.
function DynStartSt_CreateFcn(hObject, eventdata, handles)
% hObject    handle to DynStartSt (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
end

% --- Executes on button press in CalibrationBtn.
function CalibrationBtn_Callback(hObject, eventdata, handles)
% hObject    handle to CalibrationBtn (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
Start = str2double(get(handles.CalFromUserTxt, 'string')); % Fetches the user inputed start location in mm and converts to double
End = str2double(get(handles.CalToUserTxt, 'string')); % same for End position
Increment = get(handles.CalUserIncrementTxt, 'string'); % fetches the increment user inputed data asa string
Wait = get(handles.CalUserSpeedTxt, 'string'); % fetches the inputed data as a string
StartSteps = Start/0.00793750000; % computes the starting step position
handles.StartSteps = StartSteps; % stored the start steps inside the handles structure, to be fetched by anythingelse
EndSteps = End/0.00793750000; % computes the end step position
handles.EndSteps = EndSteps; % storees the end steps to be accessed by anything else
StartStepsStr = num2str(StartSteps);
EndStepsStr = num2str(EndSteps);
fprintf(handles.s, 'C0' + ' ' + StartStepsStr + ' ' + EndStepsStr + ' ' + Increment + ' ' + Wait);
% Looping the serial read commandand storing the info in an array that will
% later be sent to an excel file. The data in the array will be ploted
% every iteration
for j = StartSteps : str2num(Increment) : EndSteps %Issue here is that the user might input something that gives a decimal position...need to be an integer...must truncate)
input = fscanf(handles.s, '%c', 1);
handles.ArrayPosition(j) = j; % This will be used to plot 
if input == p
        rawPressure = 0;
        for i = 1:3 
            bitshift(rawPressure,8);
            rawPressure = bitor(rawPressure,fscanf(handles.s,'%i', 1 ));
        end %This shifts the new ineteger read form the serial input and bitwise ORs it to the previous value
else
    disp('Error communicating with arduino');% in case somthing goes wrong...
end
input = fscanf(handles.s, '%c', 1);
if input == t
        rawTemperature = 0;
        for i = 1:3 
            bitshift(rawTemperature,8);
            rawTemperature = bitor(rawTemperature,fscanf(handles.s,'%i', 1));
            
        end %This shifts the new ineteger read form the serial input and ands it to the previous value
else
    disp('Error communicating with arduino');
end
handles.PressureArray(j) = ComputePressure(handles.coefficients,rawPressure,rawTemperature); %handles.coefficients is an array that stores the 6 calibration data bytes
input = fscanf(handles.s, '%c', 1);
if input == c
        rawCapacitance = 0;
        for i = 1:2
            bitshift(rawCapacitance,8);
            rawCapacitance = bitor(rawCapacitance,fscanf(handles.s,'%i', 1));
        end %This shifts the new ineteger read form the serial input and ands it to the previous value
else
    disp('Error communicating with arduino');
end
handles.CapacitanceArray(j) = ComputeCapacitance( rawCapacitance, Input_Range );
plot(handles.axes_pressure,handles.ArrayPosition,handles.PressureArray);
plot(handles.axes_capacitance,handles.ArrayPosition,handles.CapacitanceArray);
set(handles.CurrentPositionTxt, 'String', j); 
end
xlswrite('calibrationData.xlxs',handles.ArrayPosition,handles.sheet,'A1');

xlswrite('calibrationData.xlxs',handles.PressureArray,handles.sheet,'B1');

xlswrite('calibrationData.xlxs',handles.CapacitanceArray,handles.sheet,'C1');

end
% Further imporvements would be to ask the user how he would like to name
% the file he is writing to...
% also, updating the position in the position static text would help know
% where the progession is



% --- Executes on button press in pushbutton4.
function pushbutton4_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton4 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
end


function CalFromUserTxt_Callback(hObject, eventdata, handles)
% hObject    handle to CalFromUserTxt (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of CalFromUserTxt as text
%        str2double(get(hObject,'String')) returns contents of CalFromUserTxt as a double
end

% --- Executes during object creation, after setting all properties.
function CalFromUserTxt_CreateFcn(hObject, eventdata, handles)
% hObject    handle to CalFromUserTxt (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
end



function CalToUserTxt_Callback(hObject, eventdata, handles)
% hObject    handle to CalToUserTxt (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of CalToUserTxt as text
%        str2double(get(hObject,'String')) returns contents of CalToUserTxt as a double
end

% --- Executes during object creation, after setting all properties.
function CalToUserTxt_CreateFcn(hObject, eventdata, handles)
% hObject    handle to CalToUserTxt (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
end



function CalUserIncrementTxt_Callback(hObject, eventdata, handles)
% hObject    handle to CalUserIncrementTxt (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of CalUserIncrementTxt as text
%        str2double(get(hObject,'String')) returns contents of CalUserIncrementTxt as a double
end

% --- Executes during object creation, after setting all properties.
function CalUserIncrementTxt_CreateFcn(hObject, eventdata, handles)
% hObject    handle to CalUserIncrementTxt (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
end


function CalUserSpeedTxt_Callback(hObject, eventdata, handles)
% hObject    handle to CalUserSpeedTxt (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of CalUserSpeedTxt as text
%        str2double(get(hObject,'String')) returns contents of CalUserSpeedTxt as a double
end

% --- Executes during object creation, after setting all properties.
function CalUserSpeedTxt_CreateFcn(hObject, eventdata, handles)
% hObject    handle to CalUserSpeedTxt (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
end


% --- Executes on button press in HomeButton.
function HomeButton_Callback(hObject, eventdata, handles)
% hObject    handle to HomeButton (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
fprintf(handles.s,'%s', 'G 28');
set(handles.CurrentPositionTxt, 'String', '0');
end

% --- Executes on button press in SlowMoveBtn.
function SlowMoveBtn_Callback(hObject, eventdata, handles)
% hObject    handle to SlowMoveBtn (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
end

% --- Executes on button press in FastMoveBtn.
function FastMoveBtn_Callback(hObject, eventdata, handles)
% hObject    handle to FastMoveBtn (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
end


function DesiredPositionTxt_Callback(hObject, eventdata, handles)
% hObject    handle to DesiredPositionTxt (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of DesiredPositionTxt as text
%        str2double(get(hObject,'String')) returns contents of DesiredPositionTxt as a double
end

% --- Executes during object creation, after setting all properties.
function DesiredPositionTxt_CreateFcn(hObject, eventdata, handles)
% hObject    handle to DesiredPositionTxt (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
end

% --- Executes on button press in SerialBtn.
function SerialBtn_Callback(hObject, eventdata, handles)
% hObject    handle to SerialBtn (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA
comPort = get(handles.COMportTxt,'String');
if(~exist('serialFlag','var'))
    [handles.s, handles.serialFlag]=setupSerial(comPort);
end
end



function COMportTxt_Callback(hObject, eventdata, handles)
% hObject    handle to COMportTxt (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of COMportTxt as text
%        str2double(get(hObject,'String')) returns contents of COMportTxt as a double
end

% --- Executes during object creation, after setting all properties.
function COMportTxt_CreateFcn(hObject, eventdata, handles)
% hObject    handle to COMportTxt (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
end

% --- Executes when user attempts to close figure1.
function figure1_CloseRequestFcn(hObject, eventdata, handles)
% hObject    handle to figure1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hint: delete(hObject) closes the figure
closeSerial(hObject);
delete(hObject);
end

% --- Executes on button press in pushbutton7.
function pushbutton7_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton7 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
end

% --- Executes on button press in PressureDataBtn.
function PressureDataBtn_Callback(hObject, eventdata, handles)
% hObject    handle to PressureDataBtn (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   C1 | Pressure sensitivity | SENS
%   C2 | Pressure offset | OFF
%   C3 | Temperature coefficient of pressure sensitivity | TCS
%   C4 | Temperature coefficient of pressure offset | TCO
%   C5 | Reference temperature | Tref
%   C6 | Temperature coefficient of the temperature | TEMPSENS
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fprintf(handles.s,'M0');
for j = 1:6
CurrentInput = fscanf(handles.s,'%c', 1 );
if CurrentInput == j
        databit = 0;
        for i = 1:1 
            bitshift(databit,8);
            databit = bitor(databit,fscanf(handles.s,'%i', 1 ));
        end %This shifts the new ineteger read form the serial input and bitwise ORs it to the previous value
else
    disp('Error communicating with arduino');
    
end
handles.coefficients(j) = databit;
end
end


% --- Creates and returns a handle to the GUI figure. 
function h1 = SingleUserInterface_LayoutFcn(policy)
% policy - create a new figure or use a singleton. 'new' or 'reuse'.

persistent hsingleton;
if strcmpi(policy, 'reuse') & ishandle(hsingleton)
    h1 = hsingleton;
    return;
end

appdata = [];
appdata.GUIDEOptions = struct(...
    'active_h', [], ...
    'taginfo', struct(...
    'figure', 2, ...
    'uipanel', 9, ...
    'pushbutton', 9, ...
    'edit', 11, ...
    'text', 15, ...
    'axes', 3), ...
    'override', 0, ...
    'release', 13, ...
    'resize', 'none', ...
    'accessibility', 'callback', ...
    'mfile', 1, ...
    'callbacks', 1, ...
    'singleton', 1, ...
    'syscolorfig', 1, ...
    'blocking', 0, ...
    'lastSavedFile', 'C:\Users\Ethienne\Dropbox\Ethienne\Ecole\Universitées\McGill\MEMS research\MatLab_Automation\SingleUserInterface.m', ...
    'lastFilename', 'C:\Users\Ethienne\Dropbox\Ethienne\Ecole\Universitées\McGill\MEMS research\MatLab_Automation\UserInterface.fig');
appdata.lastValidTag = 'figure1';
appdata.GUIDELayoutEditor = [];
appdata.initTags = struct(...
    'handle', [], ...
    'tag', 'figure1');

h1 = figure(...
'Units','characters',...
'CloseRequestFcn',@(hObject,eventdata)SingleUserInterface('figure1_CloseRequestFcn',hObject,eventdata,guidata(hObject)),...
'Color',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Colormap',[0 0 0.5625;0 0 0.625;0 0 0.6875;0 0 0.75;0 0 0.8125;0 0 0.875;0 0 0.9375;0 0 1;0 0.0625 1;0 0.125 1;0 0.1875 1;0 0.25 1;0 0.3125 1;0 0.375 1;0 0.4375 1;0 0.5 1;0 0.5625 1;0 0.625 1;0 0.6875 1;0 0.75 1;0 0.8125 1;0 0.875 1;0 0.9375 1;0 1 1;0.0625 1 1;0.125 1 0.9375;0.1875 1 0.875;0.25 1 0.8125;0.3125 1 0.75;0.375 1 0.6875;0.4375 1 0.625;0.5 1 0.5625;0.5625 1 0.5;0.625 1 0.4375;0.6875 1 0.375;0.75 1 0.3125;0.8125 1 0.25;0.875 1 0.1875;0.9375 1 0.125;1 1 0.0625;1 1 0;1 0.9375 0;1 0.875 0;1 0.8125 0;1 0.75 0;1 0.6875 0;1 0.625 0;1 0.5625 0;1 0.5 0;1 0.4375 0;1 0.375 0;1 0.3125 0;1 0.25 0;1 0.1875 0;1 0.125 0;1 0.0625 0;1 0 0;0.9375 0 0;0.875 0 0;0.8125 0 0;0.75 0 0;0.6875 0 0;0.625 0 0;0.5625 0 0],...
'IntegerHandle','off',...
'InvertHardcopy',get(0,'defaultfigureInvertHardcopy'),...
'MenuBar','none',...
'Name','UserInterface',...
'NumberTitle','off',...
'PaperPosition',get(0,'defaultfigurePaperPosition'),...
'Position',[103.8 9.23076923076923 173.4 52.2307692307692],...
'Resize','off',...
'HandleVisibility','callback',...
'UserData',[],...
'Tag','figure1',...
'Visible','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'MotionControls';

h2 = uipanel(...
'Parent',h1,...
'Units','characters',...
'Title','Motion Controls',...
'Clipping','on',...
'Position',[119.8 26.3846153846154 50.2 11.5384615384615],...
'Tag','MotionControls',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'HomeButton';

h3 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'Callback',@(hObject,eventdata)SingleUserInterface('HomeButton_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[12 7.61538461538462 26 1.69230769230769],...
'String','Home',...
'Tag','HomeButton',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'SlowMoveBtn';

h4 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'Callback',@(hObject,eventdata)SingleUserInterface('SlowMoveBtn_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[5.6 0.846153846153846 13.8 1.69230769230769],...
'String','Slow Move',...
'Tag','SlowMoveBtn',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'FastMoveBtn';

h5 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'Callback',@(hObject,eventdata)SingleUserInterface('FastMoveBtn_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[29.8 0.846153846153846 13.8 1.69230769230769],...
'String','Fast Move',...
'Tag','FastMoveBtn',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'DesiredPositionTxt';

h6 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)SingleUserInterface('DesiredPositionTxt_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[5.2 3.30769230769231 14.6 1.69230769230769],...
'String',{  'Edit Text' },...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)SingleUserInterface('DesiredPositionTxt_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','DesiredPositionTxt');

appdata = [];
appdata.lastValidTag = 'CurrentPositionTxt';

h7 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Position',[27.8 3.46153846153846 16.6 1.07692307692308],...
'String','Must Home',...
'Style','text',...
'Tag','CurrentPositionTxt',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Desired';

h8 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'Position',[3.8 5.69230769230769 18 1.07692307692308],...
'String','Desired Position',...
'Style','text',...
'Tag','Desired',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Current';

h9 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'Position',[31.2 5.76923076923077 10.4 1.07692307692308],...
'String','Current Position',...
'Style','text',...
'Tag','Current',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'CalibrationPanel';

h10 = uipanel(...
'Parent',h1,...
'Units','characters',...
'Title','Calibration ',...
'Clipping','on',...
'Position',[119.8 13.6923076923077 50.2 12.2307692307692],...
'Tag','CalibrationPanel',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'CalFromTxt';

h11 = uicontrol(...
'Parent',h10,...
'Units','characters',...
'Position',[6.8 8.76923076923077 10.4 1.07692307692308],...
'String','From',...
'Style','text',...
'Tag','CalFromTxt',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'CalToSt';

h12 = uicontrol(...
'Parent',h10,...
'Units','characters',...
'Position',[6.8 6.92307692307692 10.4 1.07692307692308],...
'String','To',...
'Style','text',...
'Tag','CalToSt',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'CalIncrementTxt';

h13 = uicontrol(...
'Parent',h10,...
'Units','characters',...
'Position',[6.8 5 10.4 1.15384615384615],...
'String','Increment',...
'Style','text',...
'Tag','CalIncrementTxt',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'CalSpeedSt';

h14 = uicontrol(...
'Parent',h10,...
'Units','characters',...
'Position',[6.8 3.15384615384615 10.4 1.07692307692308],...
'String','Speed',...
'Style','text',...
'Tag','CalSpeedSt',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'pushbutton4';

h15 = uicontrol(...
'Parent',h10,...
'Units','characters',...
'Callback',@(hObject,eventdata)SingleUserInterface('pushbutton4_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[3 0.615384615384615 43.6 1.69230769230769],...
'String','Start Calibration Curve  Ploting',...
'Tag','pushbutton4',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'CalFromUserTxt';

h16 = uicontrol(...
'Parent',h10,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)SingleUserInterface('CalFromUserTxt_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[29.8 8.46153846153846 10.2 1.69230769230769],...
'String','Start',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)SingleUserInterface('CalFromUserTxt_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','CalFromUserTxt');

appdata = [];
appdata.lastValidTag = 'CalToUserTxt';

h17 = uicontrol(...
'Parent',h10,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)SingleUserInterface('CalToUserTxt_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[29.8 6.53846153846154 10.2 1.69230769230769],...
'String','End',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)SingleUserInterface('CalToUserTxt_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','CalToUserTxt');

appdata = [];
appdata.lastValidTag = 'CalUserIncrementTxt';

h18 = uicontrol(...
'Parent',h10,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)SingleUserInterface('CalUserIncrementTxt_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[29.8 4.76923076923077 10.2 1.69230769230769],...
'String','Steps?',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)SingleUserInterface('CalUserIncrementTxt_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','CalUserIncrementTxt');

appdata = [];
appdata.lastValidTag = 'CalUserSpeedTxt';

h19 = uicontrol(...
'Parent',h10,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)SingleUserInterface('CalUserSpeedTxt_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[29.8 3 10.2 1.69230769230769],...
'String','Speed?',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)SingleUserInterface('CalUserSpeedTxt_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','CalUserSpeedTxt');

appdata = [];
appdata.lastValidTag = 'DynamicPanel';

h20 = uipanel(...
'Parent',h1,...
'Units','characters',...
'Title','Dynamic Testing',...
'Clipping','on',...
'Position',[119.8 1.38461538461538 50.2 12.0769230769231],...
'Tag','DynamicPanel',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'edit9';

h21 = uicontrol(...
'Parent',h20,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)SingleUserInterface('edit9_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[29.8 2.99999999999999 10.2 1.69230769230769],...
'String',{  'Edit Text' },...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)SingleUserInterface('edit9_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','edit9');

appdata = [];
appdata.lastValidTag = 'DynUserFrequencyTxt';

h22 = uicontrol(...
'Parent',h20,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)SingleUserInterface('DynUserFrequencyTxt_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[29.8 4.76923076923075 10.2 1.69230769230769],...
'String','Hz?',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)SingleUserInterface('DynUserFrequencyTxt_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','DynUserFrequencyTxt');

appdata = [];
appdata.lastValidTag = 'DynUserToTxt';

h23 = uicontrol(...
'Parent',h20,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)SingleUserInterface('DynUserToTxt_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[29.8 6.53846153846152 10.2 1.69230769230769],...
'String','End',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)SingleUserInterface('DynUserToTxt_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','DynUserToTxt');

appdata = [];
appdata.lastValidTag = 'DynStartSt';

h24 = uicontrol(...
'Parent',h20,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)SingleUserInterface('DynStartSt_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[29.8 8.30769230769229 10.2 1.69230769230769],...
'String','Start',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)SingleUserInterface('DynStartSt_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','DynStartSt');

appdata = [];
appdata.lastValidTag = 'CalibrationBtn';

h25 = uicontrol(...
'Parent',h20,...
'Units','characters',...
'Callback',@(hObject,eventdata)SingleUserInterface('CalibrationBtn_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[13.6 0.846153846153821 21.8 1.69230769230769],...
'String','Start Dynamic Test',...
'Tag','CalibrationBtn',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text9';

h26 = uicontrol(...
'Parent',h20,...
'Units','characters',...
'Position',[6.8 2.99999999999998 10.4 1.07692307692308],...
'String',{  'Static Text' },...
'Style','text',...
'Tag','text9',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'DynFrequencySt';

h27 = uicontrol(...
'Parent',h20,...
'Units','characters',...
'Position',[6.8 4.84615384615383 10.4 1.15384615384615],...
'String','Frequency',...
'Style','text',...
'Tag','DynFrequencySt',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'DynToSt';

h28 = uicontrol(...
'Parent',h20,...
'Units','characters',...
'Position',[6.8 6.76923076923075 10.4 1.07692307692308],...
'String','To',...
'Style','text',...
'Tag','DynToSt',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'DynFromSt';

h29 = uicontrol(...
'Parent',h20,...
'Units','characters',...
'Position',[6.8 8.6153846153846 10.4 1.07692307692308],...
'String','From',...
'Style','text',...
'Tag','DynFromSt',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'axes_pressure';

h30 = axes(...
'Parent',h1,...
'Units','characters',...
'Position',[19.8 30.0769230769231 80.2 19.3076923076923],...
'CameraPosition',[0.5 0.5 9.16025403784439],...
'CameraPositionMode',get(0,'defaultaxesCameraPositionMode'),...
'Color',get(0,'defaultaxesColor'),...
'ColorOrder',get(0,'defaultaxesColorOrder'),...
'LooseInset',[22.542 5.54230769230769 16.473 3.77884615384615],...
'XColor',get(0,'defaultaxesXColor'),...
'YColor',get(0,'defaultaxesYColor'),...
'ZColor',get(0,'defaultaxesZColor'),...
'Tag','axes_pressure',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

h31 = get(h30,'title');

set(h31,...
'Parent',h30,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',10,...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[0.5 1.02589641434263 1.00005459937205],...
'Rotation',0,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','bottom',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','on',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

h32 = get(h30,'xlabel');

set(h32,...
'Parent',h30,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',10,...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[0.497506234413965 -0.0936254980079683 1.00005459937205],...
'Rotation',0,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','cap',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','on',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

h33 = get(h30,'ylabel');

set(h33,...
'Parent',h30,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',10,...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[-0.071072319201995 0.49601593625498 1.00005459937205],...
'Rotation',90,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','bottom',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','on',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

h34 = get(h30,'zlabel');

set(h34,...
'Parent',h30,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',10,...
'FontWeight','normal',...
'HorizontalAlignment','right',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[-0.248129675810474 1.14143426294821 1.00005459937205],...
'Rotation',0,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','middle',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','off',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

appdata = [];
appdata.lastValidTag = 'axes_capacitance';

h35 = axes(...
'Parent',h1,...
'Units','characters',...
'Position',[19.8 4.76923076923077 80.2 19.3076923076923],...
'CameraPosition',[0.5 0.5 9.16025403784439],...
'CameraPositionMode',get(0,'defaultaxesCameraPositionMode'),...
'Color',get(0,'defaultaxesColor'),...
'ColorOrder',get(0,'defaultaxesColorOrder'),...
'LooseInset',[22.542 5.54230769230769 16.473 3.77884615384615],...
'XColor',get(0,'defaultaxesXColor'),...
'YColor',get(0,'defaultaxesYColor'),...
'ZColor',get(0,'defaultaxesZColor'),...
'Tag','axes_capacitance',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

h36 = get(h35,'title');

set(h36,...
'Parent',h35,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',10,...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[0.5 1.02589641434263 1.00005459937205],...
'Rotation',0,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','bottom',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','on',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

h37 = get(h35,'xlabel');

set(h37,...
'Parent',h35,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',10,...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[0.497506234413965 -0.0936254980079685 1.00005459937205],...
'Rotation',0,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','cap',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','on',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

h38 = get(h35,'ylabel');

set(h38,...
'Parent',h35,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',10,...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[-0.071072319201995 0.49601593625498 1.00005459937205],...
'Rotation',90,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','bottom',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','on',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

h39 = get(h35,'zlabel');

set(h39,...
'Parent',h35,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',10,...
'FontWeight','normal',...
'HorizontalAlignment','right',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[-0.248129675810474 2.45219123505976 1.00005459937205],...
'Rotation',0,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','middle',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','off',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

appdata = [];
appdata.lastValidTag = 'text12';

h40 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'Position',[39.8 50.1538461538462 40.2 1.07692307692308],...
'String','Pressure Vs Time',...
'Style','text',...
'Tag','text12',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text13';

h41 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'Position',[39.8 25.3846153846154 40.2 1.07692307692308],...
'String','Capacitance Vs Time',...
'Style','text',...
'Tag','text13',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'uipanel7';

h42 = uipanel(...
'Parent',h1,...
'Units','characters',...
'Title','Serial Communication',...
'Clipping','on',...
'Position',[119.8 43.2307692307692 50.2 8.15384615384616],...
'Tag','uipanel7',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'SerialBtn';

h43 = uicontrol(...
'Parent',h42,...
'Units','characters',...
'Callback',@(hObject,eventdata)SingleUserInterface('SerialBtn_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[9.8 0.999999999999998 32 1.69230769230769],...
'String','Connect Device',...
'Tag','SerialBtn',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text14';

h44 = uicontrol(...
'Parent',h42,...
'Units','characters',...
'Position',[8.80000000000001 5.07692307692308 34.6 1.07692307692308],...
'String','Type in Serial Port String',...
'Style','text',...
'Tag','text14',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'COMportTxt';

h45 = uicontrol(...
'Parent',h42,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)SingleUserInterface('COMportTxt_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[9.8 3.07692307692308 31.8 1.69230769230769],...
'String','COM port ?',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)SingleUserInterface('COMportTxt_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','COMportTxt');

appdata = [];
appdata.lastValidTag = 'Settings';

h46 = uipanel(...
'Parent',h1,...
'Units','characters',...
'Title','Register Setttings',...
'Clipping','on',...
'Position',[119.6 38.3846153846154 50.2 4.84615384615385],...
'Tag','Settings',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'pushbutton7';

h47 = uicontrol(...
'Parent',h46,...
'Units','characters',...
'Callback',@(hObject,eventdata)SingleUserInterface('pushbutton7_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[2.4 0.923076923076922 19.8 1.69230769230769],...
'String',{  'Push Button' },...
'Tag','pushbutton7',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'PressureDataBtn';

h48 = uicontrol(...
'Parent',h46,...
'Units','characters',...
'Callback',@(hObject,eventdata)SingleUserInterface('PressureDataBtn_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[26.4 0.923076923076922 19.2 1.69230769230769],...
'String','Pressure',...
'Tag','PressureDataBtn',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );


hsingleton = h1;


% --- Set application data first then calling the CreateFcn. 
function local_CreateFcn(hObject, eventdata, createfcn, appdata)

if ~isempty(appdata)
   names = fieldnames(appdata);
   for i=1:length(names)
       name = char(names(i));
       setappdata(hObject, name, getfield(appdata,name));
   end
end

if ~isempty(createfcn)
   if isa(createfcn,'function_handle')
       createfcn(hObject, eventdata);
   else
       eval(createfcn);
   end
end


% --- Handles default GUIDE GUI creation and callback dispatch
function varargout = gui_mainfcn(gui_State, varargin)

gui_StateFields =  {'gui_Name'
    'gui_Singleton'
    'gui_OpeningFcn'
    'gui_OutputFcn'
    'gui_LayoutFcn'
    'gui_Callback'};
gui_Mfile = '';
for i=1:length(gui_StateFields)
    if ~isfield(gui_State, gui_StateFields{i})
        error(message('MATLAB:guide:StateFieldNotFound', gui_StateFields{ i }, gui_Mfile));
    elseif isequal(gui_StateFields{i}, 'gui_Name')
        gui_Mfile = [gui_State.(gui_StateFields{i}), '.m'];
    end
end

numargin = length(varargin);

if numargin == 0
    % SINGLEUSERINTERFACE
    % create the GUI only if we are not in the process of loading it
    % already
    gui_Create = true;
elseif local_isInvokeActiveXCallback(gui_State, varargin{:})
    % SINGLEUSERINTERFACE(ACTIVEX,...)
    vin{1} = gui_State.gui_Name;
    vin{2} = [get(varargin{1}.Peer, 'Tag'), '_', varargin{end}];
    vin{3} = varargin{1};
    vin{4} = varargin{end-1};
    vin{5} = guidata(varargin{1}.Peer);
    feval(vin{:});
    return;
elseif local_isInvokeHGCallback(gui_State, varargin{:})
    % SINGLEUSERINTERFACE('CALLBACK',hObject,eventData,handles,...)
    gui_Create = false;
else
    % SINGLEUSERINTERFACE(...)
    % create the GUI and hand varargin to the openingfcn
    gui_Create = true;
end

if ~gui_Create
    % In design time, we need to mark all components possibly created in
    % the coming callback evaluation as non-serializable. This way, they
    % will not be brought into GUIDE and not be saved in the figure file
    % when running/saving the GUI from GUIDE.
    designEval = false;
    if (numargin>1 && ishghandle(varargin{2}))
        fig = varargin{2};
        while ~isempty(fig) && ~ishghandle(fig,'figure')
            fig = get(fig,'parent');
        end
        
        designEval = isappdata(0,'CreatingGUIDEFigure') || isprop(fig,'__GUIDEFigure');
    end
        
    if designEval
        beforeChildren = findall(fig);
    end
    
    % evaluate the callback now
    varargin{1} = gui_State.gui_Callback;
    if nargout
        [varargout{1:nargout}] = feval(varargin{:});
    else       
        feval(varargin{:});
    end
    
    % Set serializable of objects created in the above callback to off in
    % design time. Need to check whether figure handle is still valid in
    % case the figure is deleted during the callback dispatching.
    if designEval && ishghandle(fig)
        set(setdiff(findall(fig),beforeChildren), 'Serializable','off');
    end
else
    if gui_State.gui_Singleton
        gui_SingletonOpt = 'reuse';
    else
        gui_SingletonOpt = 'new';
    end

    % Check user passing 'visible' P/V pair first so that its value can be
    % used by oepnfig to prevent flickering
    gui_Visible = 'auto';
    gui_VisibleInput = '';
    for index=1:2:length(varargin)
        if length(varargin) == index || ~ischar(varargin{index})
            break;
        end

        % Recognize 'visible' P/V pair
        len1 = min(length('visible'),length(varargin{index}));
        len2 = min(length('off'),length(varargin{index+1}));
        if ischar(varargin{index+1}) && strncmpi(varargin{index},'visible',len1) && len2 > 1
            if strncmpi(varargin{index+1},'off',len2)
                gui_Visible = 'invisible';
                gui_VisibleInput = 'off';
            elseif strncmpi(varargin{index+1},'on',len2)
                gui_Visible = 'visible';
                gui_VisibleInput = 'on';
            end
        end
    end
    
    % Open fig file with stored settings.  Note: This executes all component
    % specific CreateFunctions with an empty HANDLES structure.

    
    % Do feval on layout code in m-file if it exists
    gui_Exported = ~isempty(gui_State.gui_LayoutFcn);
    % this application data is used to indicate the running mode of a GUIDE
    % GUI to distinguish it from the design mode of the GUI in GUIDE. it is
    % only used by actxproxy at this time.   
    setappdata(0,genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]),1);
    if gui_Exported
        gui_hFigure = feval(gui_State.gui_LayoutFcn, gui_SingletonOpt);

        % make figure invisible here so that the visibility of figure is
        % consistent in OpeningFcn in the exported GUI case
        if isempty(gui_VisibleInput)
            gui_VisibleInput = get(gui_hFigure,'Visible');
        end
        set(gui_hFigure,'Visible','off')

        % openfig (called by local_openfig below) does this for guis without
        % the LayoutFcn. Be sure to do it here so guis show up on screen.
        movegui(gui_hFigure,'onscreen');
    else
        gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);
        % If the figure has InGUIInitialization it was not completely created
        % on the last pass.  Delete this handle and try again.
        if isappdata(gui_hFigure, 'InGUIInitialization')
            delete(gui_hFigure);
            gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);
        end
    end
    if isappdata(0, genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]))
        rmappdata(0,genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]));
    end

    % Set flag to indicate starting GUI initialization
    setappdata(gui_hFigure,'InGUIInitialization',1);

    % Fetch GUIDE Application options
    gui_Options = getappdata(gui_hFigure,'GUIDEOptions');
    % Singleton setting in the GUI M-file takes priority if different
    gui_Options.singleton = gui_State.gui_Singleton;

    if ~isappdata(gui_hFigure,'GUIOnScreen')
        % Adjust background color
        if gui_Options.syscolorfig
            set(gui_hFigure,'Color', get(0,'DefaultUicontrolBackgroundColor'));
        end

        % Generate HANDLES structure and store with GUIDATA. If there is
        % user set GUI data already, keep that also.
        data = guidata(gui_hFigure);
        handles = guihandles(gui_hFigure);
        if ~isempty(handles)
            if isempty(data)
                data = handles;
            else
                names = fieldnames(handles);
                for k=1:length(names)
                    data.(char(names(k)))=handles.(char(names(k)));
                end
            end
        end
        guidata(gui_hFigure, data);
    end

    % Apply input P/V pairs other than 'visible'
    for index=1:2:length(varargin)
        if length(varargin) == index || ~ischar(varargin{index})
            break;
        end

        len1 = min(length('visible'),length(varargin{index}));
        if ~strncmpi(varargin{index},'visible',len1)
            try set(gui_hFigure, varargin{index}, varargin{index+1}), catch break, end
        end
    end

    % If handle visibility is set to 'callback', turn it on until finished
    % with OpeningFcn
    gui_HandleVisibility = get(gui_hFigure,'HandleVisibility');
    if strcmp(gui_HandleVisibility, 'callback')
        set(gui_hFigure,'HandleVisibility', 'on');
    end

    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

    if isscalar(gui_hFigure) && ishghandle(gui_hFigure)
        % Handle the default callbacks of predefined toolbar tools in this
        % GUI, if any
        guidemfile('restoreToolbarToolPredefinedCallback',gui_hFigure); 
        
        % Update handle visibility
        set(gui_hFigure,'HandleVisibility', gui_HandleVisibility);

        % Call openfig again to pick up the saved visibility or apply the
        % one passed in from the P/V pairs
        if ~gui_Exported
            gui_hFigure = local_openfig(gui_State.gui_Name, 'reuse',gui_Visible);
        elseif ~isempty(gui_VisibleInput)
            set(gui_hFigure,'Visible',gui_VisibleInput);
        end
        if strcmpi(get(gui_hFigure, 'Visible'), 'on')
            figure(gui_hFigure);
            
            if gui_Options.singleton
                setappdata(gui_hFigure,'GUIOnScreen', 1);
            end
        end

        % Done with GUI initialization
        if isappdata(gui_hFigure,'InGUIInitialization')
            rmappdata(gui_hFigure,'InGUIInitialization');
        end

        % If handle visibility is set to 'callback', turn it on until
        % finished with OutputFcn
        gui_HandleVisibility = get(gui_hFigure,'HandleVisibility');
        if strcmp(gui_HandleVisibility, 'callback')
            set(gui_hFigure,'HandleVisibility', 'on');
        end
        gui_Handles = guidata(gui_hFigure);
    else
        gui_Handles = [];
    end

    if nargout
        [varargout{1:nargout}] = feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);
    else
        feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);
    end

    if isscalar(gui_hFigure) && ishghandle(gui_hFigure)
        set(gui_hFigure,'HandleVisibility', gui_HandleVisibility);
    end
end

function gui_hFigure = local_openfig(name, singleton, visible)

% openfig with three arguments was new from R13. Try to call that first, if
% failed, try the old openfig.
if nargin('openfig') == 2
    % OPENFIG did not accept 3rd input argument until R13,
    % toggle default figure visible to prevent the figure
    % from showing up too soon.
    gui_OldDefaultVisible = get(0,'defaultFigureVisible');
    set(0,'defaultFigureVisible','off');
    gui_hFigure = openfig(name, singleton);
    set(0,'defaultFigureVisible',gui_OldDefaultVisible);
else
    gui_hFigure = openfig(name, singleton, visible);  
    %workaround for CreateFcn not called to create ActiveX
    if feature('HGUsingMATLABClasses')
        peers=findobj(findall(allchild(gui_hFigure)),'type','uicontrol','style','text');    
        for i=1:length(peers)
            if isappdata(peers(i),'Control')
                actxproxy(peers(i));
            end            
        end
    end
end

function result = local_isInvokeActiveXCallback(gui_State, varargin)

try
    result = ispc && iscom(varargin{1}) ...
             && isequal(varargin{1},gcbo);
catch
    result = false;
end

function result = local_isInvokeHGCallback(gui_State, varargin)

try
    fhandle = functions(gui_State.gui_Callback);
    result = ~isempty(findstr(gui_State.gui_Name,fhandle.file)) || ...
             (ischar(varargin{1}) ...
             && isequal(ishghandle(varargin{2}), 1) ...
             && (~isempty(strfind(varargin{1},[get(varargin{2}, 'Tag'), '_'])) || ...
                ~isempty(strfind(varargin{1}, '_CreateFcn'))) );
catch
    result = false;
end


